#!/bin/bash
#
# Bluespec compiler driver for CMake
#
set -e

function join_by 
{ 
    local IFS="$1"; shift; echo "$*"; 
}

VERBOSE=false

function log
{
    if [ "$VERBOSE" = "true" ]; then 
        echo "$*"
    fi
}

BSV_COMPILER="bsc"

#
# verify compiler exists
#
if ! command -v $BSV_COMPILER &> /dev/null
then
    echo "[bsvar] ERROR: bsc executable could not be found in system PATH."
    exit 1
fi

#
# Parse options
#
OUTPUT=""

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"

    case $key in
        -o|--output)
            OUTPUT="$2"
            shift # past argument
            shift # past value
            ;;
        -v|--verbose)
            VERBOSE=true
            shift # past argument
            ;;
        *)    # unknown option
            log "[bsvar] OPTIONAL ARGUMENT: $1"
            POSITIONAL+=("$1") # save it in an array for later
            shift # past argument
            ;;
  esac
done

if [ ${#POSITIONAL[@]} -eq 0 ]; then
    echo "[bsvar] ERROR: No input files specified."
    exit 1
fi

if [ -z "$OUTPUT" ]; then
    echo "[bsvar] ERROR: -o option is required"
    exit 1
fi

# Archive Mode
mkdir -p "$OUTPUT"

for OBJECT_FILE in "${POSITIONAL[@]}"
do
    TARGET_NAME=$(basename "$OBJECT_FILE" .bsv.bo)
    cp "${OBJECT_FILE}" "${OUTPUT}/${TARGET_NAME}.bo"
done
