#!/bin/bash
#
# Bluespec compiler driver for CMake
#
set -e

function join_by 
{ 
    local IFS="$1"; shift; echo "$*"; 
}

VERBOSE=false

function log
{
    if [ "$VERBOSE" = "true" ]; then 
        echo "$*"
    fi
}

BSV_COMPILER="bsc"

#
# verify compiler exists
#
if ! command -v $BSV_COMPILER &> /dev/null
then
    echo "[bsvc] ERROR: bsc executable could not be found in system PATH."
    exit 1
fi

#
# Parse options
#
OUTPUT=""
INCLUDE_DIRECTORIES=("%/Libraries")

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"

    case $key in
        -o|--output)
            OUTPUT="$2"
            shift # past argument
            shift # past value
            ;;
        -I)
            INCLUDE_DIRECTORIES+=("$2")
            shift # past argument
            shift # past value
            ;;
        --archive)
            ARCHIVE=true
            shift
            ;;
        -v|--verbose)
            VERBOSE=true
            shift # past argument
            ;;
        *)    # unknown option
            POSITIONAL+=("$1") # save it in an array for later
            shift # past argument
            ;;
  esac
done

if [ ${#POSITIONAL[@]} -eq 0 ]; then
    echo "[bsvc] ERROR: No input files specified."
    exit 1
fi

if [ "$ARCHIVE" != "true" ] && [ ${#POSITIONAL[@]} -gt 1 ]; then
    echo "[bsvc] ERROR: Extra arguments detected."
    exit 1
fi

if [ -z "$OUTPUT" ]; then
    echo "[bsvc] ERROR: -o option is required"
    exit 1
fi

if [ "$ARCHIVE" != "true" ]; then
    INPUT_FILE=${POSITIONAL[0]}

    # Create the include directory spec by joining all directories specified
    # delimited by a colon ':'
    #
    INCLUDE_DIRECTORIES_SPEC=$(join_by : "${INCLUDE_DIRECTORIES[@]}")

    # Determine the output directory based on the dirname of the output specified
    OUTPUT_DIR=$(dirname "$OUTPUT")
    SOURCE_DIR=$(dirname "$INPUT_FILE")

    log "[bsvc] Command Line: '$BSV_COMPILER -u -bdir $OUTPUT_DIR -p $SOURCE_DIR:$INCLUDE_DIRECTORIES_SPEC $INPUT_FILE'"

    # Run the compiler
    $BSV_COMPILER -u -bdir "$OUTPUT_DIR" -p "$SOURCE_DIR:$INCLUDE_DIRECTORIES_SPEC" "$INPUT_FILE"

    # bsc outputs foo.bo for inputs of foo.bsv which may not be what CMake expects.
    # If the output file is different than what CMake expects copy it.
    OUTPUT_FILENAME_EXPECTED=$(basename "$OUTPUT")
    OUTPUT_FILENAME_ACTUAL=$(basename "$INPUT_FILE" .bsv).bo

    if [ "$OUTPUT_FILENAME_EXPECTED" != "$OUTPUT_NAME_ACTUAL" ]; then
        OUTPUT_FILE_SOURCE="$OUTPUT_DIR/$OUTPUT_FILENAME_ACTUAL"
        OUTPUT_FILE_DEST="$OUTPUT_DIR/$OUTPUT_FILENAME_EXPECTED"

        log "[bsvc] Copying $OUTPUT_FILE_SOURCE to $OUTPUT_FILE_DEST"
        cp "$OUTPUT_FILE_SOURCE" "$OUTPUT_FILE_DEST"
    fi
else
    # Archive Mode
    mkdir -p "$OUTPUT"

    for OBJECT_FILE in "${POSITIONAL[@]}"
    do
        TARGET_NAME=$(basename $OBJECT_FILE .bsv.bo)
        cp "${OBJECT_FILE}" "${OUTPUT}/${TARGET_NAME}.bo"
    done
fi
